worker_heartbeat_timeout: 300000

logging:
    level: info

services:
  - module: lib/index.js
    entrypoint: apiServiceWorker
    conf:
        #userAgent: 'My-User-Agent-String'
        mwApis:
        ${:mwApis}
        #- uri: 'http://localhost/w/api.php'
        #  domain: 'localhost'  # optional
